<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>llhd</string>
	</array>
	<key>name</key>
	<string>LLHD</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#instructions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9\.]*[muµnpf]?s)\b</string>
			<key>name</key>
			<string>constant.numeric.time.llhd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%[0-9][a-zA-Z0-9\_.]*)\b</string>
			<key>name</key>
			<string>variable.local.temp.llhd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(@[a-zA-Z0-9\_.]+)\b</string>
			<key>name</key>
			<string>variable.global.llhd</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%[a-zA-Z0-9\_.]+)\b</string>
			<key>name</key>
			<string>variable.local.llhd</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[#;]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.llhd</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.llhd</string>
				</dict>
			</array>
		</dict>
		<key>instructions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(and|or|xor|nand|nor|not|add|sub|mul|div|delay|st)\b</string>
					<key>name</key>
					<string>keyword.instruction.llhd</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(define|process|storage)\b</string>
					<key>name</key>
					<string>keyword.llhd</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(in|out|reg|wire|var)\b</string>
					<key>name</key>
					<string>storage.llhd</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(l)[0-9]+\b</string>
					<key>name</key>
					<string>storage.type.llhd</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.llhd</string>
	<key>uuid</key>
	<string>2189438b-8dab-4549-be42-dd6a0b982c1e</string>
</dict>
</plist>
