/* Copyright (c) 2014 Fabian Schuiki */
#include <fstream>
#include <iostream>

/// \file Reads the `CaseFolding.txt` file which is part of the Unicode
/// Character database, and digests its information into an efficient mapping
/// structure which is written to disk.

int main(int argc, char** argv)
{
	// Verify we have enough arguments.
	if (argc != 3) {
		std::cerr << "usage: " << argv[0] << " <input> <output>\n";
		return 1;
	}

	// Open the file for reading.
	std::ifstream fin(argv[1]);
	if (!fin.good()) {
		std::cerr << "unable to open input file for writing\n";
		return 2;
	}

	// Parse the input file and generate the different table versions.
	while (fin.good()) {

		// Skip empty lines.
		if (fin.peek() == '\n') {
			fin.get();
			continue;
		}

		// Skip comment lines.
		if (fin.peek() == '#') {
			while (fin.get() != '\n' && fin.good());
			continue;
		}

		// Abort in case the peeking caused the stream to reach its end.
		if (!fin.good())
			break;

		unsigned code;
		char status;
		unsigned mapping[16] = {0};

		fin >> std::hex >> code;
		while (fin.peek() == ';' || fin.peek() == ' ')
			fin.get();
		fin >> status;
		while (fin.peek() == ';' || fin.peek() == ' ')
			fin.get();

		unsigned i;
		for (i = 0; i < 15;) {
			fin >> std::hex >> mapping[i++];
			if (fin.peek() == ';')
				break;
			while (fin.peek() == ' ')
				fin.get();
		}
		mapping[i] = 0;
		while (fin.get() != '\n' && fin.good());

		std::cout << "read code point " << std::hex << code << ", status " << status << ", mapping " << mapping[0] << ':' << mapping[1] << ':' << mapping[2] << '\n';
	}

	// Open the file for writing.
	std::ofstream fout(argv[2]);
	if (!fout.good()) {
		std::cerr << "unable to open output file for writing\n";
		return 3;
	}
	fout << "/* This file was automatically generated by unicode-gen-casefolding. DO NOT MODIFY. */\n";

	return 0;
}
