/* This file was automatically generated by vhdl-tblgen-keywords. DO NOT MODIFY. */
#pragma once
#include "llhd/vhdl/TokenType.hpp"

namespace llhd {
namespace vhdl {

template<class InputIterator>
unsigned lookupKeyword(InputIterator first, InputIterator last) {
	InputIterator i = first;
	if (i == last) {
		return 0;
	} else if (*i == 'a') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'b') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 's') {
				++i;
				if (i == last) {
					return kKeywordAbs;
				}
			}
		} else if (*i == 'c') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'c') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 's') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 's') {
							++i;
							if (i == last) {
								return kKeywordAccess;
							}
						}
					}
				}
			}
		} else if (*i == 'f') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return kKeywordAfter;
						}
					}
				}
			}
		} else if (*i == 'l') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'i') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'a') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 's') {
						++i;
						if (i == last) {
							return kKeywordAlias;
						}
					}
				}
			} else if (*i == 'l') {
				++i;
				if (i == last) {
					return kKeywordAll;
				}
			}
		} else if (*i == 'n') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'd') {
				++i;
				if (i == last) {
					return kKeywordAnd;
				}
			}
		} else if (*i == 'r') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'c') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'h') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'i') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 't') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'e') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'c') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 't') {
										++i;
										if (i == last) {
											return 0;
										} else if (*i == 'u') {
											++i;
											if (i == last) {
												return 0;
											} else if (*i == 'r') {
												++i;
												if (i == last) {
													return 0;
												} else if (*i == 'e') {
													++i;
													if (i == last) {
														return kKeywordArchitecture;
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'a') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'y') {
						++i;
						if (i == last) {
							return kKeywordArray;
						}
					}
				}
			}
		} else if (*i == 's') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 's') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 't') {
							++i;
							if (i == last) {
								return kKeywordAssert;
							}
						}
					}
				}
			}
		} else if (*i == 't') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'r') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'i') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'b') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'u') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 't') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'e') {
										++i;
										if (i == last) {
											return kKeywordAttribute;
										}
									}
								}
							}
						}
					}
				}
			}
		}
	} else if (*i == 'b') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'e') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'g') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'i') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'n') {
						++i;
						if (i == last) {
							return kKeywordBegin;
						}
					}
				}
			}
		} else if (*i == 'l') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'o') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'c') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'k') {
						++i;
						if (i == last) {
							return kKeywordBlock;
						}
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'd') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'y') {
					++i;
					if (i == last) {
						return kKeywordBody;
					}
				}
			}
		} else if (*i == 'u') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'f') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'f') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'e') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'r') {
							++i;
							if (i == last) {
								return kKeywordBuffer;
							}
						}
					}
				}
			} else if (*i == 's') {
				++i;
				if (i == last) {
					return kKeywordBus;
				}
			}
		}
	} else if (*i == 'c') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 's') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return kKeywordCase;
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'm') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'p') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'o') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'n') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'e') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'n') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 't') {
										++i;
										if (i == last) {
											return kKeywordComponent;
										}
									}
								}
							}
						}
					}
				}
			} else if (*i == 'n') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'f') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'i') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'g') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'u') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'r') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'a') {
										++i;
										if (i == last) {
											return 0;
										} else if (*i == 't') {
											++i;
											if (i == last) {
												return 0;
											} else if (*i == 'i') {
												++i;
												if (i == last) {
													return 0;
												} else if (*i == 'o') {
													++i;
													if (i == last) {
														return 0;
													} else if (*i == 'n') {
														++i;
														if (i == last) {
															return kKeywordConfiguration;
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				} else if (*i == 's') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 't') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'a') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'n') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 't') {
									++i;
									if (i == last) {
										return kKeywordConstant;
									}
								}
							}
						}
					}
				}
			}
		}
	} else if (*i == 'd') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'i') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 's') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'c') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'o') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'n') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'n') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'e') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'c') {
										++i;
										if (i == last) {
											return 0;
										} else if (*i == 't') {
											++i;
											if (i == last) {
												return kKeywordDisconnect;
											}
										}
									}
								}
							}
						}
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'w') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'n') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 't') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'o') {
							++i;
							if (i == last) {
								return kKeywordDownto;
							}
						}
					}
				}
			}
		}
	} else if (*i == 'e') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'l') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 's') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return kKeywordElse;
					}
				} else if (*i == 'i') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'f') {
						++i;
						if (i == last) {
							return kKeywordElsif;
						}
					}
				}
			}
		} else if (*i == 'n') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'd') {
				++i;
				if (i == last) {
					return kKeywordEnd;
				}
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'i') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 't') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'y') {
							++i;
							if (i == last) {
								return kKeywordEntity;
							}
						}
					}
				}
			}
		} else if (*i == 'x') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'i') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return kKeywordExit;
					}
				}
			}
		}
	} else if (*i == 'f') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'i') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'l') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return kKeywordFile;
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return kKeywordFor;
				}
			}
		} else if (*i == 'u') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'n') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'c') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 't') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'i') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'o') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'n') {
									++i;
									if (i == last) {
										return kKeywordFunction;
									}
								}
							}
						}
					}
				}
			}
		}
	} else if (*i == 'g') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'e') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'n') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'a') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 't') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'e') {
									++i;
									if (i == last) {
										return kKeywordGenerate;
									}
								}
							}
						} else if (*i == 'i') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'c') {
								++i;
								if (i == last) {
									return kKeywordGeneric;
								}
							}
						}
					}
				}
			}
		} else if (*i == 'r') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'o') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'u') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'p') {
						++i;
						if (i == last) {
							return kKeywordGroup;
						}
					}
				}
			}
		} else if (*i == 'u') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'a') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'r') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'd') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'e') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'd') {
								++i;
								if (i == last) {
									return kKeywordGuarded;
								}
							}
						}
					}
				}
			}
		}
	} else if (*i == 'i') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'f') {
			++i;
			if (i == last) {
				return kKeywordIf;
			}
		} else if (*i == 'm') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'p') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'u') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'e') {
							++i;
							if (i == last) {
								return kKeywordImpure;
							}
						}
					}
				}
			}
		} else if (*i == 'n') {
			++i;
			if (i == last) {
				return kKeywordIn;
			} else if (*i == 'e') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'r') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 't') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'i') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'a') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'l') {
									++i;
									if (i == last) {
										return kKeywordInertial;
									}
								}
							}
						}
					}
				}
			} else if (*i == 'o') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'u') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 't') {
						++i;
						if (i == last) {
							return kKeywordInout;
						}
					}
				}
			}
		} else if (*i == 's') {
			++i;
			if (i == last) {
				return kKeywordIs;
			}
		}
	} else if (*i == 'l') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'b') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'l') {
						++i;
						if (i == last) {
							return kKeywordLabel;
						}
					}
				}
			}
		} else if (*i == 'i') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'b') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'r') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'a') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'r') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'y') {
								++i;
								if (i == last) {
									return kKeywordLibrary;
								}
							}
						}
					}
				}
			} else if (*i == 'n') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'k') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'a') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'g') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'e') {
								++i;
								if (i == last) {
									return kKeywordLinkage;
								}
							}
						}
					}
				}
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'a') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'l') {
								++i;
								if (i == last) {
									return kKeywordLiteral;
								}
							}
						}
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'o') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'p') {
					++i;
					if (i == last) {
						return kKeywordLoop;
					}
				}
			}
		}
	} else if (*i == 'm') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'p') {
				++i;
				if (i == last) {
					return kKeywordMap;
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'd') {
				++i;
				if (i == last) {
					return kKeywordMod;
				}
			}
		}
	} else if (*i == 'n') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'n') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'd') {
					++i;
					if (i == last) {
						return kKeywordNand;
					}
				}
			}
		} else if (*i == 'e') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'w') {
				++i;
				if (i == last) {
					return kKeywordNew;
				}
			} else if (*i == 'x') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return kKeywordNext;
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return kKeywordNor;
				}
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return kKeywordNot;
				}
			}
		} else if (*i == 'u') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'l') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'l') {
					++i;
					if (i == last) {
						return kKeywordNull;
					}
				}
			}
		}
	} else if (*i == 'o') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'f') {
			++i;
			if (i == last) {
				return kKeywordOf;
			}
		} else if (*i == 'n') {
			++i;
			if (i == last) {
				return kKeywordOn;
			}
		} else if (*i == 'p') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'e') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'n') {
					++i;
					if (i == last) {
						return kKeywordOpen;
					}
				}
			}
		} else if (*i == 'r') {
			++i;
			if (i == last) {
				return kKeywordOr;
			}
		} else if (*i == 't') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'h') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 's') {
							++i;
							if (i == last) {
								return kKeywordOthers;
							}
						}
					}
				}
			}
		} else if (*i == 'u') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return kKeywordOut;
				}
			}
		}
	} else if (*i == 'p') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'c') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'k') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'a') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'g') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'e') {
								++i;
								if (i == last) {
									return kKeywordPackage;
								}
							}
						}
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return kKeywordPort;
					}
				}
			} else if (*i == 's') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'p') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'o') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'n') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'e') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'd') {
										++i;
										if (i == last) {
											return kKeywordPostponed;
										}
									}
								}
							}
						}
					}
				}
			}
		} else if (*i == 'r') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'o') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'c') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'e') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'd') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'u') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'r') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'a') {
										++i;
										if (i == last) {
											return 0;
										} else if (*i == 'l') {
											++i;
											if (i == last) {
												return kKeywordProcedural;
											}
										}
									} else if (*i == 'e') {
										++i;
										if (i == last) {
											return kKeywordProcedure;
										}
									}
								}
							}
						} else if (*i == 's') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 's') {
								++i;
								if (i == last) {
									return kKeywordProcess;
								}
							}
						}
					}
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'e') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'c') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 't') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'e') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'd') {
										++i;
										if (i == last) {
											return kKeywordProtected;
										}
									}
								}
							}
						}
					}
				}
			}
		} else if (*i == 'u') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return kKeywordPure;
					}
				}
			}
		}
	} else if (*i == 'r') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'n') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'g') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'e') {
						++i;
						if (i == last) {
							return kKeywordRange;
						}
					}
				}
			}
		} else if (*i == 'e') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'c') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'o') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'd') {
							++i;
							if (i == last) {
								return kKeywordRecord;
							}
						}
					}
				}
			} else if (*i == 'f') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'e') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'n') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'c') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'e') {
										++i;
										if (i == last) {
											return kKeywordReference;
										}
									}
								}
							}
						}
					}
				}
			} else if (*i == 'g') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'i') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 's') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 't') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'e') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'r') {
									++i;
									if (i == last) {
										return kKeywordRegister;
									}
								}
							}
						}
					}
				}
			} else if (*i == 'j') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'c') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 't') {
							++i;
							if (i == last) {
								return kKeywordReject;
							}
						}
					}
				}
			} else if (*i == 'm') {
				++i;
				if (i == last) {
					return kKeywordRem;
				}
			} else if (*i == 'p') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'o') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 't') {
							++i;
							if (i == last) {
								return kKeywordReport;
							}
						}
					}
				}
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'u') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'n') {
							++i;
							if (i == last) {
								return kKeywordReturn;
							}
						}
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'l') {
				++i;
				if (i == last) {
					return kKeywordRol;
				}
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return kKeywordRor;
				}
			}
		}
	} else if (*i == 's') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'e') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'l') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'c') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 't') {
							++i;
							if (i == last) {
								return kKeywordSelect;
							}
						}
					}
				}
			} else if (*i == 'v') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'r') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'i') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 't') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'y') {
									++i;
									if (i == last) {
										return kKeywordSeverity;
									}
								}
							}
						}
					}
				}
			}
		} else if (*i == 'h') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'a') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'r') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'e') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'd') {
							++i;
							if (i == last) {
								return kKeywordShared;
							}
						}
					}
				}
			}
		} else if (*i == 'i') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'g') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'n') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'a') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'l') {
							++i;
							if (i == last) {
								return kKeywordSignal;
							}
						}
					}
				}
			}
		} else if (*i == 'l') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'a') {
				++i;
				if (i == last) {
					return kKeywordSla;
				}
			} else if (*i == 'l') {
				++i;
				if (i == last) {
					return kKeywordSll;
				}
			}
		} else if (*i == 'r') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'a') {
				++i;
				if (i == last) {
					return kKeywordSra;
				}
			} else if (*i == 'l') {
				++i;
				if (i == last) {
					return kKeywordSrl;
				}
			}
		} else if (*i == 'u') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'b') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'y') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'p') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'e') {
								++i;
								if (i == last) {
									return kKeywordSubtype;
								}
							}
						}
					}
				}
			}
		}
	} else if (*i == 't') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'h') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'e') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'n') {
					++i;
					if (i == last) {
						return kKeywordThen;
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return kKeywordTo;
			}
		} else if (*i == 'r') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'a') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'n') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 's') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'p') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'o') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'r') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 't') {
										++i;
										if (i == last) {
											return kKeywordTransport;
										}
									}
								}
							}
						}
					}
				}
			}
		} else if (*i == 'y') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'p') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'e') {
					++i;
					if (i == last) {
						return kKeywordType;
					}
				}
			}
		}
	} else if (*i == 'u') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'n') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'a') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'f') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'f') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'e') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'c') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 't') {
									++i;
									if (i == last) {
										return 0;
									} else if (*i == 'e') {
										++i;
										if (i == last) {
											return 0;
										} else if (*i == 'd') {
											++i;
											if (i == last) {
												return kKeywordUnaffected;
											}
										}
									}
								}
							}
						}
					}
				}
			} else if (*i == 'i') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 's') {
						++i;
						if (i == last) {
							return kKeywordUnits;
						}
					}
				}
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'i') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'l') {
						++i;
						if (i == last) {
							return kKeywordUntil;
						}
					}
				}
			}
		} else if (*i == 's') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'e') {
				++i;
				if (i == last) {
					return kKeywordUse;
				}
			}
		}
	} else if (*i == 'v') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'i') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'a') {
						++i;
						if (i == last) {
							return 0;
						} else if (*i == 'b') {
							++i;
							if (i == last) {
								return 0;
							} else if (*i == 'l') {
								++i;
								if (i == last) {
									return 0;
								} else if (*i == 'e') {
									++i;
									if (i == last) {
										return kKeywordVariable;
									}
								}
							}
						}
					}
				}
			}
		}
	} else if (*i == 'w') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'a') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'i') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 't') {
					++i;
					if (i == last) {
						return kKeywordWait;
					}
				}
			}
		} else if (*i == 'h') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'e') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'n') {
					++i;
					if (i == last) {
						return kKeywordWhen;
					}
				}
			} else if (*i == 'i') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'l') {
					++i;
					if (i == last) {
						return 0;
					} else if (*i == 'e') {
						++i;
						if (i == last) {
							return kKeywordWhile;
						}
					}
				}
			}
		} else if (*i == 'i') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 't') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'h') {
					++i;
					if (i == last) {
						return kKeywordWith;
					}
				}
			}
		}
	} else if (*i == 'x') {
		++i;
		if (i == last) {
			return 0;
		} else if (*i == 'n') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'o') {
				++i;
				if (i == last) {
					return 0;
				} else if (*i == 'r') {
					++i;
					if (i == last) {
						return kKeywordXnor;
					}
				}
			}
		} else if (*i == 'o') {
			++i;
			if (i == last) {
				return 0;
			} else if (*i == 'r') {
				++i;
				if (i == last) {
					return kKeywordXor;
				}
			}
		}
	}
	return 0;
}

} // namespace vhdl
} // namespace llhd
